# -*- coding: utf-8 -*-
"""App portafolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYD2Ofu-bHmoPP-ybPcxj0fQHT86Tanr
"""

import streamlit as st
import pandas as pd

st.title('Analisis de portafolio de inversion')