# -*- coding: utf-8 -*-
"""Aplicacion portafolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYD2Ofu-bHmoPP-ybPcxj0fQHT86Tanr
"""

import streamlit as st
import pandas as pd

st.title('ANÁLISIS DE PORTAFOLIO DE INVERSIÓN')

st.markdown('**INTEGRANTES DEL GRUPO**')

st.markdown('Andrea Velasquez')

st.markdown('Blanca Alvarez')

Temas=['Definición','Tipos de analisis de portafolio', 'Selección de la propuesta', 'Herramienta', 'Referencias']

Tema_seleccionado=st.selectbox('selecciona un tema;', Temas)

st.write('Has seleccionado:', Tema_seleccionado)

if Tema_seleccionado=='Definición':
    st.write('''**ANALISIS DE PORTAFOLIO DE INVERSIÓN:**

Un Análisis de Portafolio de Inversión consiste en estudiar y evaluar el conjunto de activos financieros (acciones, bonos, bienes raíces, entre otros) en el que una persona o empresa ha invertido. El objetivo de este análisis es entender cómo se comportan esos activos, tanto en términos de riesgo como de rentabilidad.

**Principios elementales de inversión**.
En todo instrumento financiero de un portafolio de inversión tienen
que considerarse los siguientes elementos:

- ***Rendimiento***: Es la ganancia que se obtendría y está dada en función a la tasa y al plazo de inversión.

Es la estimación de las ganancias que se espera obtener de las inversiones a lo largo del tiempo. Este rendimiento puede variar dependiendo de las condiciones del mercado, pero es importante proyectarlo para tomar decisiones informadas.

- ***Riesgo***:Se refiere a la posibilidad de que los rendimientos no se den como se esperaba. En este contexto, se suelen usar herramientas estadísticas como la volatilidad (que mide las fluctuaciones de los precios de los activos), la varianza y la desviación estándar para cuantificar cuán impredecibles o inestables son los rendimientos.

Debe determinarse cuánto riesgo se está dispuesto a asumir.

- ***Diversificación y correlación***: Uno de los principios clave en la gestión de un portafolio es diversificar. Esto significa invertir en diferentes tipos de activos que no se muevan de manera idéntica. La correlación entre los activos muestra si sus rendimientos tienden a moverse juntos o en direcciones opuestas. Idealmente, se buscan activos con baja correlación entre sí, para reducir el riesgo total del portafolio.

Es decir, en lugar de invertir todo el capital en un solo activo (como, por ejemplo, solo en acciones de una empresa), se distribuye entre diferentes activos, clases de activos o mercados. Al hacer esto, se busca minimizar el impacto de los posibles rendimientos negativos de un activo específico.

- ***Relación riesgo-retorno***: Un análisis de portafolio también evalúa si el rendimiento que se espera obtener justifica el riesgo que se asume. Es decir, busca encontrar un balance entre obtener buenos rendimientos sin exponerse a un riesgo excesivo.

**En resumen**, Un portafolio de inversión es un conjunto de activos financieros que se combinan para generar rendimientos con un nivel de riesgo controlado. La diversificación busca repartir el dinero entre diferentes activos para reducir riesgos, mientras que la correlación mide cómo se comportan esos activos entre sí. El objetivo es equilibrar el riesgo y el retorno para optimizar las ganancias.

Es una herramienta crucial para los inversionistas que buscan maximizar su rentabilidad y minimizar los riesgos asociados con sus decisiones financieras.''')